version: "3.9"

services:
  database:
    image: postgres
    container_name: timos_database
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=timos
    volumes:
      - pgdata:/data/postgres

  # app:
  #   build: .
  #   container_name: timos
  #   restart: always
  #   ports:
  #     - 3333:3333
  #     - 9229:9229
  #   environment:
  #     - RUN_COMMAND=${DOCKER_RUN_COMMAND}
  #   volumes:
  #     - .:/usr/app
  #   links:
  #     - database
  #   depends_on:
  #     - database

volumes:
  pgdata:
    driver: local